<?php
session_start();
require 'includes/db.php';

if (!isset($_SESSION['loggedin']) || $_SESSION['loggedin'] !== true) {
    header("Location: index.php");
    exit;
}
require_once __DIR__ . '/vendor/autoload.php'; // mPDF autoload

if (!isset($_GET['id']) || !is_numeric($_GET['id'])) {
    die('Invalid Sale ID');
}

$sale_id = $_GET['id'];

// Fetch sale info + customer name
$sale = $pdo->prepare("
    SELECT s.*, c.name AS customer_name
    FROM sales s
    JOIN customers c ON s.customer_id = c.id
    WHERE s.id = ?
");
$sale->execute([$sale_id]);
$sale = $sale->fetch(PDO::FETCH_ASSOC);

if (!$sale) {
    die('Sale not found');
}

// Fetch all sale items
$items_stmt = $pdo->prepare("SELECT * FROM sale_items WHERE sale_id=?");
$items_stmt->execute([$sale_id]);
$items = $items_stmt->fetchAll(PDO::FETCH_ASSOC);

// Initialize mPDF
$mpdf = new \Mpdf\Mpdf(['format' => 'A4']);

// Build PDF HTML
$html = '
<style>
body { font-family: sans-serif; font-size: 12px; }
.header { text-align:center; font-size:18px; font-weight:bold; color:#0078d7; margin-bottom:10px; }
table { width:100%; border-collapse: collapse; margin-top:10px; }
th, td { border:1px solid #aaa; padding:6px; text-align:center; }
th { background:#0078d7; color:white; }
.footer { margin-top:20px; font-size:12px; }
</style>

<div class="header">AT Optical ERP — Sales Report</div>
<table>
  <tr>
    <td><strong>Sale ID:</strong> ' . htmlspecialchars($sale['id']) . '</td>
    <td><strong>Date:</strong> ' . htmlspecialchars($sale['created_at']) . '</td>
  </tr>
  <tr>
    <td><strong>Customer:</strong> ' . htmlspecialchars($sale['customer_name']) . '</td>
    <td><strong>Note:</strong> ' . htmlspecialchars($sale['note']) . '</td>
  </tr>
</table>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Type</th>
      <th>Item Name</th>
      <th>Spherical</th>
      <th>Cylinder</th>
      <th>Axis</th>
      <th>Addition</th>
      <th>Qty</th>
      <th>Rate</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>';

$total = 0;
$count = 1;
foreach ($items as $item) {
    $amount = $item['amount'];
    $total += $amount;
    $html .= '
    <tr>
      <td>' . $count++ . '</td>
      <td>' . htmlspecialchars($item['item_type']) . '</td>
      <td>' . htmlspecialchars($item['item_name']) . '</td>
      <td>' . htmlspecialchars($item['spherical']) . '</td>
      <td>' . htmlspecialchars($item['cylinder']) . '</td>
      <td>' . htmlspecialchars($item['axis']) . '</td>
      <td>' . htmlspecialchars($item['addition']) . '</td>
      <td>' . htmlspecialchars($item['quantity']) . '</td>
      <td>' . number_format($item['rate'], 2) . '</td>
      <td>' . number_format($amount, 2) . '</td>
    </tr>';
}

$html .= '
    <tr>
      <td colspan="9" style="text-align:right;"><strong>Total:</strong></td>
      <td><strong>' . number_format($total, 2) . '</strong></td>
    </tr>
    <tr>
      <td colspan="9" style="text-align:right;">Paid Amount:</td>
      <td>' . number_format($sale['paid_amount'], 2) . '</td>
    </tr>
    <tr>
      <td colspan="9" style="text-align:right;">Remaining:</td>
      <td>' . number_format($sale['remaining_amount'], 2) . '</td>
    </tr>
  </tbody>
</table>

<div class="footer">
  <p><strong>Generated By:</strong> AT Optical ERP</p>
  <p>Date: ' . date('d M, Y h:i A') . '</p>
</div>
';

// Output PDF inline
$mpdf->WriteHTML($html);
$mpdf->Output('sales_report_' . $sale_id . '.pdf', 'I');
