<?php
require 'includes/session.php';
require 'includes/db.php';
require_once __DIR__ . '/vendor/autoload.php'; // mPDF autoload path

if (!isset($_GET['id']) || !is_numeric($_GET['id'])) {
    die('Invalid Purchase ID');
}

$purchase_id = $_GET['id'];

// Fetch purchase info
$purchase = $pdo->prepare("
    SELECT p.*, s.name AS supplier_name 
    FROM purchases p 
    JOIN suppliers s ON p.supplier_id = s.id 
    WHERE p.id = ?
");
$purchase->execute([$purchase_id]);
$purchase = $purchase->fetch(PDO::FETCH_ASSOC);

if (!$purchase) {
    die('Purchase not found');
}

// Since items are stored in same table, we'll treat this as single item record
$items = [$purchase];

// Initialize mPDF
$mpdf = new \Mpdf\Mpdf(['format' => 'A4']);

// HTML content for PDF
$html = '
<style>
body { font-family: sans-serif; font-size: 12px; }
.header { text-align:center; font-size:18px; font-weight:bold; color:#0078d7; margin-bottom:10px; }
table { width:100%; border-collapse: collapse; margin-top:10px; }
th, td { border:1px solid #aaa; padding:6px; text-align:center; }
th { background:#0078d7; color:white; }
.footer { margin-top:20px; font-size:12px; }
</style>

<div class="header">AT Optical ERP — Purchase Report</div>
<table>
  <tr>
    <td><strong>Purchase ID:</strong> ' . htmlspecialchars($purchase['id']) . '</td>
    <td><strong>Date:</strong> ' . htmlspecialchars($purchase['created_at']) . '</td>
  </tr>
  <tr>
    <td><strong>Supplier:</strong> ' . htmlspecialchars($purchase['supplier_name']) . '</td>
    <td><strong>Note:</strong> ' . htmlspecialchars($purchase['note']) . '</td>
  </tr>
</table>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Type</th>
      <th>Item Name</th>
      <th>Spherical</th>
      <th>Cylinder</th>
      <th>Qty</th>
      <th>Rate</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>';

$total = 0;
$count = 1;
foreach ($items as $item) {
    $amount = $item['total_amount'];
    $total += $amount;
    $html .= '
    <tr>
      <td>' . $count++ . '</td>
      <td>' . htmlspecialchars($item['item_type']) . '</td>
      <td>' . htmlspecialchars($item['item_name']) . '</td>
      <td>' . htmlspecialchars($item['spherical']) . '</td>
      <td>' . htmlspecialchars($item['cylinder']) . '</td>
      <td>' . htmlspecialchars($item['quantity']) . '</td>
      <td>' . number_format($item['rate'], 2) . '</td>
      <td>' . number_format($amount, 2) . '</td>
    </tr>';
}

$html .= '
    <tr>
      <td colspan="7" style="text-align:right;"><strong>Total:</strong></td>
      <td><strong>' . number_format($total, 2) . '</strong></td>
    </tr>
    <tr>
      <td colspan="7" style="text-align:right;">Paid Amount:</td>
      <td>' . number_format($purchase['paid_amount'], 2) . '</td>
    </tr>
    <tr>
      <td colspan="7" style="text-align:right;">Remaining:</td>
      <td>' . number_format($purchase['remaining_amount'], 2) . '</td>
    </tr>
  </tbody>
</table>

<div class="footer">
  <p><strong>Generated By:</strong> AT Optical ERP</p>
  <p>Date: ' . date('d M, Y h:i A') . '</p>
</div>
';

// Output PDF
$mpdf->WriteHTML($html);
$mpdf->Output('purchase_report_' . $purchase_id . '.pdf', 'I');
